plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { name = "CurseMaven"; url "https://cursemaven.com" }
    maven { name = "Modrinth"; url = "https://api.modrinth.com/maven" }
    maven { name = "Ladysnake Mods"; url = 'https://maven.ladysnake.org/releases' }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:1.21.5"
    mappings "net.fabricmc:yarn:1.21.5+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.14"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.128.1+1.21.5"

    implementation(include 'org.javassist:javassist:3.29.2-GA')
    implementation(include 'org.reflections:reflections:0.10.2')
    modImplementation(include 'maven.modrinth:trinkets-canary:3.11.0-1.21.5')

    modApi(include 'org.ladysnake.cardinal-components-api:cardinal-components-base:6.3.1')
    modApi(include 'org.ladysnake.cardinal-components-api:cardinal-components-entity:6.3.1')
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}